services:
  pg_test:
    image: postgres:16.8
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test

  mysql_test:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  clickhouse_test:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9001:9000"
    environment:
      CLICKHOUSE_DB: "test"
      CLICKHOUSE_USER: "test"
      CLICKHOUSE_PASSWORD: "test"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "test"
